variable "name_prefix" {
  description = "Resource name prefix (project-environment)"
  type        = string
}

variable "db_password" {
  description = "Master DB password generated by the RDS module"
  type        = string
  sensitive   = true
}
