"""add_consent_logs_dsr_requests

Revision ID: 3ba082c27b6d
Revises: f6dafa9f0006
Create Date: 2026-05-31 12:31:37.515670+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '3ba082c27b6d'
down_revision: str | None = 'f6dafa9f0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('event_type', sa.Enum('cookie_accept', 'cookie_reject', 'privacy_accept', 'marketing_opt_in', 'marketing_opt_out', name='consenteventtype'), nullable=False),
    sa.Column('ip_addr', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('consent_logs_pkey'))
    )
    op.create_index(op.f('consent_logs_event_type_idx'), 'consent_logs', ['event_type'], unique=False)
    op.create_index(op.f('consent_logs_session_id_idx'), 'consent_logs', ['session_id'], unique=False)
    op.create_index(op.f('consent_logs_user_id_idx'), 'consent_logs', ['user_id'], unique=False)
    op.create_table('dsr_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('request_type', sa.Enum('deletion', 'export', 'access', name='dsrtype'), nullable=False),
    sa.Column('fb_user_id', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'rejected', name='dsrstatus'), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('dsr_requests_pkey'))
    )
    op.create_index(op.f('dsr_requests_email_idx'), 'dsr_requests', ['email'], unique=False)
    op.create_index(op.f('dsr_requests_status_idx'), 'dsr_requests', ['status'], unique=False)
    op.alter_column('chat_messages', 'platform',
               existing_type=postgresql.ENUM('messenger', 'web', name='messageplatform'),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('customer_clusters_slug_key'), 'customer_clusters', type_='unique')
    op.drop_index(op.f('customer_clusters_slug_idx'), table_name='customer_clusters')
    op.create_index(op.f('customer_clusters_slug_idx'), 'customer_clusters', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('customer_clusters_slug_idx'), table_name='customer_clusters')
    op.create_index(op.f('customer_clusters_slug_idx'), 'customer_clusters', ['slug'], unique=False)
    op.create_unique_constraint(op.f('customer_clusters_slug_key'), 'customer_clusters', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('chat_messages', 'platform',
               existing_type=postgresql.ENUM('messenger', 'web', name='messageplatform'),
               server_default=sa.text("'messenger'::messageplatform"),
               existing_nullable=False)
    op.drop_index(op.f('dsr_requests_status_idx'), table_name='dsr_requests')
    op.drop_index(op.f('dsr_requests_email_idx'), table_name='dsr_requests')
    op.drop_table('dsr_requests')
    op.drop_index(op.f('consent_logs_user_id_idx'), table_name='consent_logs')
    op.drop_index(op.f('consent_logs_session_id_idx'), table_name='consent_logs')
    op.drop_index(op.f('consent_logs_event_type_idx'), table_name='consent_logs')
    op.drop_table('consent_logs')
    # ### end Alembic commands ###
