"""initial DHTC schema

Revision ID: deb529662590
Revises: 
Create Date: 2026-05-16 14:54:48.864285+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'deb529662590'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_vi', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(
        ['parent_id'], ['categories.id'],
        name=op.f('categories_parent_id_fkey'),
    ),
    sa.PrimaryKeyConstraint('id', name=op.f('categories_pkey'))
    )
    op.create_index(op.f('categories_parent_id_idx'), 'categories', ['parent_id'], unique=False)
    op.create_index(op.f('categories_slug_idx'), 'categories', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'seller', 'customer', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('users_email_idx'), 'users', ['email'], unique=True)
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shop_name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description_vi', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('banner_url', sa.String(length=500), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column(
        'tier',
        sa.Enum('bronze', 'silver', 'gold', name='merchanttier'),
        nullable=False,
    ),
    sa.Column(
        'status',
        sa.Enum('pending', 'active', 'suspended', name='merchantstatus'),
        nullable=False,
    ),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('merchants_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('merchants_pkey'))
    )
    op.create_index(op.f('merchants_slug_idx'), 'merchants', ['slug'], unique=True)
    op.create_index(op.f('merchants_user_id_idx'), 'merchants', ['user_id'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column(
        'status',
        sa.Enum(
            'pending', 'processing', 'shipped', 'delivered', 'cancelled',
            name='orderstatus',
        ),
        nullable=False,
    ),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_address', sa.JSON(), nullable=False),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(
        ['customer_id'], ['users.id'],
        name=op.f('orders_customer_id_fkey'),
    ),
    sa.ForeignKeyConstraint(
        ['merchant_id'], ['merchants.id'],
        name=op.f('orders_merchant_id_fkey'),
    ),
    sa.PrimaryKeyConstraint('id', name=op.f('orders_pkey'))
    )
    op.create_index(op.f('orders_customer_id_idx'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('orders_merchant_id_idx'), 'orders', ['merchant_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name_vi', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('sold_count', sa.Integer(), nullable=False),
    sa.Column(
        'status',
        sa.Enum('active', 'pending', 'inactive', name='productstatus'),
        nullable=False,
    ),
    sa.Column('description_vi', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('origin', sa.String(length=200), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(
        ['category_id'], ['categories.id'],
        name=op.f('products_category_id_fkey'),
    ),
    sa.ForeignKeyConstraint(
        ['merchant_id'], ['merchants.id'],
        name=op.f('products_merchant_id_fkey'),
    ),
    sa.PrimaryKeyConstraint('id', name=op.f('products_pkey'))
    )
    op.create_index(op.f('products_category_id_idx'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('products_merchant_id_idx'), 'products', ['merchant_id'], unique=False)
    op.create_index(op.f('products_slug_idx'), 'products', ['slug'], unique=False)
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('percentage', 'fixed', name='promotiontype'), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_order', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('max_usage', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(
        ['merchant_id'], ['merchants.id'],
        name=op.f('promotions_merchant_id_fkey'),
    ),
    sa.PrimaryKeyConstraint('id', name=op.f('promotions_pkey'))
    )
    op.create_index(op.f('promotions_code_idx'), 'promotions', ['code'], unique=False)
    op.create_index(op.f('promotions_merchant_id_idx'), 'promotions', ['merchant_id'], unique=False)
    op.create_table('shipping_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('zone_name', sa.String(length=100), nullable=False),
    sa.Column('countries', sa.JSON(), nullable=False),
    sa.Column('base_rate', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('per_kg_rate', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('estimated_days_min', sa.Integer(), nullable=False),
    sa.Column('estimated_days_max', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(
        ['merchant_id'], ['merchants.id'],
        name=op.f('shipping_zones_merchant_id_fkey'),
    ),
    sa.PrimaryKeyConstraint('id', name=op.f('shipping_zones_pkey'))
    )
    op.create_index(
        op.f('shipping_zones_merchant_id_idx'),
        'shipping_zones', ['merchant_id'], unique=False,
    )
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(
        ['customer_id'], ['users.id'],
        name=op.f('cart_items_customer_id_fkey'),
    ),
    sa.ForeignKeyConstraint(
        ['product_id'], ['products.id'],
        name=op.f('cart_items_product_id_fkey'),
    ),
    sa.PrimaryKeyConstraint('id', name=op.f('cart_items_pkey')),
    sa.UniqueConstraint('customer_id', 'product_id', name=op.f('cart_items_customer_id_key'))
    )
    op.create_index(op.f('cart_items_customer_id_idx'), 'cart_items', ['customer_id'], unique=False)
    op.create_index(op.f('cart_items_product_id_idx'), 'cart_items', ['product_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('order_items_order_id_fkey')),
    sa.ForeignKeyConstraint(
        ['product_id'], ['products.id'],
        name=op.f('order_items_product_id_fkey'),
    ),
    sa.PrimaryKeyConstraint('id', name=op.f('order_items_pkey'))
    )
    op.create_index(op.f('order_items_order_id_idx'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('order_items_product_id_idx'), 'order_items', ['product_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('reviews_customer_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('reviews_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reviews_pkey')),
    sa.UniqueConstraint('customer_id', 'product_id', name=op.f('reviews_customer_id_key'))
    )
    op.create_index(op.f('reviews_customer_id_idx'), 'reviews', ['customer_id'], unique=False)
    op.create_index(op.f('reviews_product_id_idx'), 'reviews', ['product_id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column(
        'type',
        sa.Enum(
            'sale', 'withdrawal', 'fee', 'adjustment',
            name='transactiontype',
        ),
        nullable=False,
    ),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(
        ['merchant_id'], ['merchants.id'],
        name=op.f('wallet_transactions_merchant_id_fkey'),
    ),
    sa.ForeignKeyConstraint(
        ['reference_order_id'], ['orders.id'],
        name=op.f('wallet_transactions_reference_order_id_fkey'),
    ),
    sa.PrimaryKeyConstraint('id', name=op.f('wallet_transactions_pkey'))
    )
    op.create_index(
        op.f('wallet_transactions_merchant_id_idx'),
        'wallet_transactions', ['merchant_id'], unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('wallet_transactions_merchant_id_idx'),
        table_name='wallet_transactions',
    )
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('reviews_product_id_idx'), table_name='reviews')
    op.drop_index(op.f('reviews_customer_id_idx'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('order_items_product_id_idx'), table_name='order_items')
    op.drop_index(op.f('order_items_order_id_idx'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('cart_items_product_id_idx'), table_name='cart_items')
    op.drop_index(op.f('cart_items_customer_id_idx'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('shipping_zones_merchant_id_idx'), table_name='shipping_zones')
    op.drop_table('shipping_zones')
    op.drop_index(op.f('promotions_merchant_id_idx'), table_name='promotions')
    op.drop_index(op.f('promotions_code_idx'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('products_slug_idx'), table_name='products')
    op.drop_index(op.f('products_merchant_id_idx'), table_name='products')
    op.drop_index(op.f('products_category_id_idx'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('orders_merchant_id_idx'), table_name='orders')
    op.drop_index(op.f('orders_customer_id_idx'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('merchants_user_id_idx'), table_name='merchants')
    op.drop_index(op.f('merchants_slug_idx'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_index(op.f('users_email_idx'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('categories_slug_idx'), table_name='categories')
    op.drop_index(op.f('categories_parent_id_idx'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
