"""add_return_requests

Revision ID: c33041c5f002
Revises: 756deeca985d
Create Date: 2026-05-17 11:38:11.191191+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = 'c33041c5f002'
down_revision: str | None = '756deeca985d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('return_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column(
        'status',
        sa.Enum('pending', 'approved', 'rejected', name='returnstatus'),
        nullable=False,
    ),
    sa.Column('seller_note', sa.Text(), nullable=True),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(
        ['customer_id'], ['users.id'],
        name=op.f('return_requests_customer_id_fkey'),
        ondelete='CASCADE',
    ),
    sa.ForeignKeyConstraint(
        ['order_id'], ['orders.id'],
        name=op.f('return_requests_order_id_fkey'),
        ondelete='CASCADE',
    ),
    sa.PrimaryKeyConstraint('id', name=op.f('return_requests_pkey'))
    )
    op.create_index(
        op.f('return_requests_customer_id_idx'),
        'return_requests', ['customer_id'], unique=False,
    )
    op.create_index(
        op.f('return_requests_order_id_idx'),
        'return_requests', ['order_id'], unique=True,
    )
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-17 07:53:11.969431+00'::timestamp with time zone"),
               existing_nullable=False)
    op.drop_index(op.f('return_requests_order_id_idx'), table_name='return_requests')
    op.drop_index(op.f('return_requests_customer_id_idx'), table_name='return_requests')
    op.drop_table('return_requests')
    # ### end Alembic commands ###
