"""add notifications table and order notes

Revision ID: 756deeca985d
Revises: b4c9f1d2e3a8
Create Date: 2026-05-17 07:53:06.371011+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '756deeca985d'
down_revision: str | None = 'b4c9f1d2e3a8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('order_new', 'order_confirmed', 'order_shipped', 'order_delivered', 'order_cancelled', 'product_approved', 'product_rejected', 'withdrawal_approved', 'withdrawal_rejected', 'review_received', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('notifications_user_id_idx'), 'notifications', ['user_id'], unique=False)
    op.add_column('orders', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.drop_column('orders', 'notes')
    op.drop_index(op.f('notifications_user_id_idx'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
