"""add_order_events_addresses_wishlist

Revision ID: a009b6b556b6
Revises: 0abf0af8a4fe
Create Date: 2026-05-17 03:23:04.282406+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = 'a009b6b556b6'
down_revision: str | None = '0abf0af8a4fe'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_addresses_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_addresses_pkey'))
    )
    op.create_index(op.f('user_addresses_user_id_idx'), 'user_addresses', ['user_id'], unique=False)
    op.create_table('order_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'processing', 'shipped', 'delivered', 'cancelled', name='orderstatus', create_type=False), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('order_events_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('order_events_pkey'))
    )
    op.create_index(op.f('order_events_order_id_idx'), 'order_events', ['order_id'], unique=False)
    op.create_table('wishlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('wishlist_items_product_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('wishlist_items_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('wishlist_items_pkey')),
    sa.UniqueConstraint('user_id', 'product_id', name=op.f('wishlist_items_user_id_key'))
    )
    op.create_index(op.f('wishlist_items_product_id_idx'), 'wishlist_items', ['product_id'], unique=False)
    op.create_index(op.f('wishlist_items_user_id_idx'), 'wishlist_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('wishlist_items_user_id_idx'), table_name='wishlist_items')
    op.drop_index(op.f('wishlist_items_product_id_idx'), table_name='wishlist_items')
    op.drop_table('wishlist_items')
    op.drop_index(op.f('order_events_order_id_idx'), table_name='order_events')
    op.drop_table('order_events')
    op.drop_index(op.f('user_addresses_user_id_idx'), table_name='user_addresses')
    op.drop_table('user_addresses')
    # ### end Alembic commands ###
