"""add_user_full_name_phone

Revision ID: 7eaa66378a06
Revises: a009b6b556b6
Create Date: 2026-05-17 03:53:53.002900+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '7eaa66378a06'
down_revision: str | None = 'a009b6b556b6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
